### ISSUE TITLE
Is "String[]" as default return?

### ISSUE THREAD

**Issue by SeniorCtrlPlayer** [JuliaText/Embeddings.jl#35]
https://github.com/JuliaText/Embeddings.jl/blob/306c04bead62b32873dedbc2609c74c4ca34306b/src/Embeddings.jl#L39

I can't understand why there is a `String[]`, if T is in `supported_languages_files`, `String[]` won't be return, or it will throw an `Error`

**Comment by SeniorCtrlPlayer** [comment]
And as default return, `get!(supported_languages_files, T, String[])` is better than `do...end`

**Comment by oxinabox** [comment]
> I can't understand why there is a String[], if T is in supported_languages_files, String[] won't be return, or it will throw an Error

If there are no language files for a language loaded yet, then the collection of language files is empty, so far.
`String[]` returns an empty vector of strings (it is the same as `Vector{String}()`)
We need to return that empty collection so that we can add languages files to it:

https://github.com/JuliaText/Embeddings.jl/blob/306c04bead62b32873dedbc2609c74c4ca34306b/src/word2vec.jl#L22
https://github.com/JuliaText/Embeddings.jl/blob/306c04bead62b32873dedbc2609c74c4ca34306b/src/fasttext.jl#L79-L80

> And as default return, get!(supported_languages_files, T, String[]) is better than do...end

They are basically the same.

**Comment by SeniorCtrlPlayer** [comment]
@oxinabox I got it, thanks
But, there is a weird Error. The default return seems to must be same type as any value in the array.
For example:
```julia
a=Dict("a"=>1)
function test(id)
    get!(a, id) do
        String[] # Error
    end
end
```
`MethodError: Cannot convert an object of type Array{String,1} to an object of type Int64`
```julia
a=Dict("a"=>1)
function test(id)
    get!(a, id) do
        a # right
    end
end
```
This will work when `id` not in `a`

**Comment by oxinabox** [comment]
Yes, `get!` stores the default value into the dictionary.

For general julia questions, I recommend
http://discourse.julialang.org/
